name: hisinet_test
channels:
  - conda-forge
  - defaults

dependencies:
  # Conda‑managed packages:
  - python==3.12.0
  - numpy>=1.18.0
  - scipy>=1.5.2
  - frozendict
  - cython
  - scikit-image
  - scikit-learn
  - seaborn
  - ipykernel
  - jupyter
  - pip
  - pip:
    - torch == 2.7.0
    - torchvision == 0.22.0
    - cooler
    - hic-straw
    - wandb